robot:
  name: Misfit01
  connected: False
  UDP_IP: 127.0.0.1
  UDP_PORT: 5005

BR_Leg:
  coax_loc: 0
  femur_loc: 1
  tibia_loc: 2

  coax_min_pulse: 1000
  coax_max_pulse: 2000
  femur_min_pulse: 1000
  femur_max_pulse: 2000
  tibia_min_pulse: 1000
  tibia_max_pulse: 2000

  coax_length: 2.5
  femur_length: 4.0
  tibia_length: 4.5

  min_x: -5
  max_x: 5
  min_y: -5
  max_y: 5
  min_z: -5
  max_z: 5

  inverse: True